apiVersion: v1
kind: Namespace
metadata:
  name: agritech-dev
  labels:
    app.kubernetes.io/part-of: agritech-marketplace
    environment: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: agritech-prod
  labels:
    app.kubernetes.io/part-of: agritech-marketplace
    environment: prod
