apiVersion: v1
kind: Service
metadata:
  name: agritech-frontend-svc
  labels:
    {{- include "agritech.labels" . | nindent 4 }}
    component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "agritech.name" . }}
    component: frontend
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
      name: http
